name: Deploy VitePress to GitHub Pages

on:
  push:
    branches:
      - docs

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 'latest'
          global: true  # 将 pnpm 安装为全局工具

      - name: Install dependencies
        run: pnpm install

      - name: Build VitePress
        run: pnpm run docs:build

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: vitepress-dist
          path: docs/.vitepress/dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          publish_dir: docs/.vitepress/dist
          publish_branch: gh-pages
