name: Deploy VitePress site to Pages

on:
  push:
    branches: [docs]

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js and pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 'latest'
          global: true

      - name: Install dependencies
        run: pnpm install

      - name: Build VitePress
        run: |
          pnpm run docs:build

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: github-pages
          path: docs/.vitepress/dist

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          publish_dir: docs/.vitepress/dist
          publish_branch: gh-pages
